version: '3.8'
services:
  # Contenedor de PHP y Apache
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./App:/var/www/html

  # Contenedor de la primera base de datos MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AppCS
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Contenedor de la segunda base de datos MySQL
  db2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PruebaBD
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - db2_data:/var/lib/mysql

  # Contenedor de PHPMyAdmin para la primera base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret

  # Contenedor de PHPMyAdmin para la segunda base de datos
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    links:
      - db2
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db2
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data:
  db2_data:
